import Head from "next/head";
import Link from "next/link";
import { useAuth } from "../context/AuthContext";
import homeStyles from "../styles/modules/Home.module.scss";
import styles from "../styles/modules/Layout.module.scss";

interface Props {
	title: string;
	children: React.ReactNode;
}

const Layout = (props: Props) => {
	const { user } = useAuth();

	return (
		<div className={homeStyles.container}>
			<Head>
				<title>{props.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className={styles.header_wrapper}>
				<div className="container">
					<div className={styles.header}>
						<div>
							<Link href={"/"}>SpotifyTopTracks</Link>
						</div>
						<div>
							<Link href={"/login"}>{<div>{user?.images.length && <img src={user?.images[0].url} alt="profile image" />}</div>}</Link>
						</div>
					</div>
				</div>
			</header>

			<main className={homeStyles.main}>{props.children}</main>

			<footer className={homeStyles.footer}></footer>
		</div>
	);
};

export default Layout;
